services:
  vue_app:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=/api/
    volumes:
      - static-data:/vol/static  # copies Vue build output on a shared with nginx container volume
    command: sh -c "npm run build && cp -r dist/* /vol/static/"

volumes:
  static-data:

networks:
  default:
    external: true
    name: myretirement_docker_network