services:
  vue_app:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api/
    ports: 
      - 5173:5173
    volumes:
      - .:/app  # every change of the current dir gets pulled by the container's workdir
      - /app/node_modules # isolates the node_modules inside and outside of our container
    command: "npm run dev -- --host 0.0.0.0 --port 5173"
    
networks:
  default:
    external: true
    name: myretirement_docker_network